### ISSUE TITLE
Scoped CSS: Support a variable mechanism

### ISSUE THREAD

**Issue by KnisterPeter** [sinnerschrader/schlump#11]
> Support a variable mechanism, or more general: shared information and/or context.

@marionebl: What do you mean by shared information and/or context?

Extension to #5

**Comment by marionebl** [comment]
I meant this kind of pattern commonly found in styling code bases:

```css
/* vars.css */
:root {
  --primary: reds;
}
```

```css
/* call-site.css */
@import "vars.css";

a {
  color: var(--primary);  
}
```

The variable declarations bleed automatically through the `@import` statement, creating a context of sorts. I guess one wants to mimic this mechanic to match developer expectations, even when picking a JavaScript based approach.
