### ISSUE TITLE
CSS Vars: interitance does not resolve variables

### ISSUE THREAD

**Issue by KnisterPeter** [sinnerschrader/schlump#35]
If, in a scope, a variable is overwritten with a variable value that values is not resovled.

For example:

```css
.root {
    --var-a: 0px;
    --var-b: 10px;
    --var-c: var(--var-a);
}
.element1 {
    --var-c: var(--var-b);
}
.element2 {
    margin: var(--var-c);
}
```
```html
<div className="root">
    <div className="element1">
        <div className="element2">
            <!-- margin should be 10px -->
            <!-- margin is currently var(--var-b) -->
            foo
        </div>
    </div>
</div>
```
