### ISSUE TITLE
Scoped CSS: create declarations in rules where variables have changed

### ISSUE THREAD

**Issue by KnisterPeter** [sinnerschrader/schlump#44]
## Stylesheet
```css
.some {
  --var: red;
  color: var(--var);
}
.some:hover {
  --var: blue;
}
```

## Expected
```css
.some {
  --var: red;
  color: red;
}
.some:hover {
  --var: blue;
  color: blue;
}
```
